<!--- Licensed to the Apache Software Foundation (ASF) under one -->
<!--- or more contributor license agreements.  See the NOTICE file -->
<!--- distributed with this work for additional information -->
<!--- regarding copyright ownership.  The ASF licenses this file -->
<!--- to you under the Apache License, Version 2.0 (the -->
<!--- "License"); you may not use this file except in compliance -->
<!--- with the License.  You may obtain a copy of the License at -->

<!---   http://www.apache.org/licenses/LICENSE-2.0 -->

<!--- Unless required by applicable law or agreed to in writing, -->
<!--- software distributed under the License is distributed on an -->
<!--- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY -->
<!--- KIND, either express or implied.  See the License for the -->
<!--- specific language governing permissions and limitations -->
<!--- under the License. -->

# Step 1: Manipulate data with NP on MXNet

This getting started exercise introduces the MXNet `np` package for ndarrays.
These ndarrays extend the functionality of the common NumPy ndarrays, by adding
support for gpu's and by adding auto-differentiation with autograd. Now, many
NumPy methods are available within MXNet; therefore, we will only briefly cover
some of what is available.

## Import packages and create an array
To get started, run the following commands to import the `np` package together
with the NumPy extensions package `npx`. Together, `np` with `npx` make up the
NP on MXNet front end.

In [1]:
import mxnet as mx
from mxnet import np, npx
npx.set_np()  # Activate NumPy-like mode.

In this step, create a 2D array (also called a matrix). The following code
example creates a matrix with values from two sets of numbers: 1, 2, 3 and 4, 5,
6. This might also be referred to as a tuple of a tuple of integers.

In [2]:
np.array(((1, 2, 3), (5, 6, 7)))

[08:53:23] /work/mxnet/src/storage/storage.cc:199: Using Pooled (Naive) StorageManager for CPU


array([[1., 2., 3.],
       [5., 6., 7.]])

You can also create a very simple matrix with the same shape (2 rows by 3
columns), but fill it with 1's.

In [3]:
x = np.full((2, 3), 1) 
x

array([[1., 1., 1.],
       [1., 1., 1.]])

Alternatively, you could use the following array creation routine.

In [4]:
x = np.ones((2, 3)) 
x

array([[1., 1., 1.],
       [1., 1., 1.]])

You can create arrays whose values are sampled randomly. For example, sampling
values uniformly between -1 and 1. The following code example creates the same
shape, but with random sampling.

In [5]:
y = np.random.uniform(-1, 1, (2, 3))
y

array([[0.09762704, 0.18568921, 0.43037868],
       [0.6885315 , 0.20552671, 0.71589124]])

As with NumPy, the dimensions of each ndarray are shown by accessing the
`.shape` attribute. As the following code example shows, you can also query for
`size`, which is equal to the product of the components of the shape. In
addition, `.dtype` tells the data type of the stored values. As you notice when
we generate random uniform values we generate `float32` not `float64` as normal
NumPy arrays.

In [6]:
(x.shape, x.size, x.dtype)

((2, 3), 6, dtype('float32'))

You could also specifiy the datatype when you create your ndarray.

In [7]:
x = np.full((2, 3), 1, dtype="int8") 
x.dtype

dtype('int8')

Versus the default of `float32`.

In [8]:
x = np.full((2, 3), 1) 
x.dtype

dtype('float32')

When we multiply, by default we use the datatype with the most precision.

In [9]:
x = x.astype("int8") + x.astype(int) + x.astype("float32")
x.dtype

dtype('float32')

## Performing operations on an array

A ndarray supports a large number of standard mathematical operations. Here are
some examples. You can perform element-wise multiplication by using the
following code example.

In [10]:
x * y

array([[0.29288113, 0.55706763, 1.291136  ],
       [2.0655947 , 0.6165801 , 2.1476736 ]])

You can perform exponentiation by using the following code example.

In [11]:
np.exp(y)

array([[1.1025515, 1.204048 , 1.5378398],
       [1.9907899, 1.2281718, 2.0460093]])

You can also find a matrix’s transpose to compute a proper matrix-matrix product
by using the following code example.

In [12]:
np.dot(x, y.T)

array([[2.1410847, 4.8298483],
       [2.1410847, 4.8298483]])

Alternatively, you could use the matrix multiplication function.

In [13]:
np.matmul(x, y.T)

array([[2.1410847, 4.8298483],
       [2.1410847, 4.8298483]])

You can leverage built in operators, like summation.

In [14]:
x.sum()

array(18.)

You can also gather a mean value.

In [15]:
x.mean()

array(3.)

You can perform flatten and reshape just like you normally would in NumPy!

In [16]:
x.flatten()

array([3., 3., 3., 3., 3., 3.])

In [17]:
x.reshape(6, 1)

array([[3.],
       [3.],
       [3.],
       [3.],
       [3.],
       [3.]])

## Indexing an array

The ndarrays support slicing in many ways you might want to access your data.
The following code example shows how to read a particular element, which returns
a 1D array with shape `(1,)`.

In [18]:
y[1, 2]

array(0.71589124)

This example shows how to read the second and third columns from `y`.

In [19]:
y[:, 1:3]

array([[0.18568921, 0.43037868],
       [0.20552671, 0.71589124]])

This example shows how to write to a specific element.

In [20]:
y[:, 1:3] = 2
y

array([[0.09762704, 2.        , 2.        ],
       [0.6885315 , 2.        , 2.        ]])

You can perform multi-dimensional slicing, which is shown in the following code
example.

In [21]:
y[1:2, 0:2] = 4
y

array([[0.09762704, 2.        , 2.        ],
       [4.        , 4.        , 2.        ]])

## Converting between MXNet ndarrays and NumPy arrays

You can convert MXNet ndarrays to and from NumPy ndarrays, as shown in the
following example. The converted arrays do not share memory.

In [22]:
a = x.asnumpy()
(type(a), a)

(numpy.ndarray,
 array([[3., 3., 3.],
        [3., 3., 3.]], dtype=float32))

In [23]:
a = np.array(a)
(type(a), a)

(mxnet.numpy.ndarray,
 array([[3., 3., 3.],
        [3., 3., 3.]]))

Additionally, you can move them to different GPU contexts. You will dive more
into this later, but here is an example for now.

In [24]:
a.copyto(mx.gpu(0))

[08:53:26] /work/mxnet/src/storage/storage.cc:199: Using Pooled (Naive) StorageManager for GPU


array([[3., 3., 3.],
       [3., 3., 3.]], ctx=gpu(0))

## Next Steps

Ndarrays also have some additional features which make Deep Learning possible
and efficient. Namely, differentiation, and being able to leverage GPU's.
Another important feature of ndarrays that we will discuss later is 
autograd. But first, we will abstract an additional level and talk about building
Neural Network Layers [Step 2: Create a neural network](./2-create-nn.ipynb)