<!--- Licensed to the Apache Software Foundation (ASF) under one -->
<!--- or more contributor license agreements.  See the NOTICE file -->
<!--- distributed with this work for additional information -->
<!--- regarding copyright ownership.  The ASF licenses this file -->
<!--- to you under the Apache License, Version 2.0 (the -->
<!--- "License"); you may not use this file except in compliance -->
<!--- with the License.  You may obtain a copy of the License at -->

<!---   http://www.apache.org/licenses/LICENSE-2.0 -->

<!--- Unless required by applicable law or agreed to in writing, -->
<!--- software distributed under the License is distributed on an -->
<!--- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY -->
<!--- KIND, either express or implied.  See the License for the -->
<!--- specific language governing permissions and limitations -->
<!--- under the License. -->

# The NP on MXNet cheat sheet

To begin, import the `np` and `npx` module and update MXNet to run in
NumPy-like mode.

In [1]:
from mxnet import np, npx
npx.set_np()  # Change MXNet to the numpy-like mode.

NDArray figure (TODO)

## Creating arrays

In [2]:
np.array([1, 2, 3])  # default datatype is float32

[22:43:26] /work/mxnet/src/storage/storage.cc:202: Using Pooled (Naive) StorageManager for CPU


array([1., 2., 3.])

In [3]:
np.array([(1.5, 2, 3), (4, 5, 6)], dtype='float16')

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]], dtype=float16)

In [4]:
np.array([[(15,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype='int32')

array([[[15,  2,  3],
        [ 4,  5,  6]],

       [[ 3,  2,  1],
        [ 4,  5,  6]]], dtype=int32)

### Initial placeholders

In [5]:
np.zeros((3, 4))  # Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2, 3, 4), dtype='int8')  # Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [7]:
np.arange(10, 25, 5)  # Create an array of evenly spaced values (step value)

array([10., 15., 20.])

In [8]:
# Create an array of evenly spaced values (number of samples)
# np.linspace(0, 2, 9)

In [9]:
# np.full((2, 2), 7)  # Create a constant array

In [10]:
# np.eye(2)  # Create a 2X2 identity matrix

In [11]:
# np.random.random((2, 2))  # Create an array with random values

In [12]:
np.empty((3,2))  # Create an empty array

array([[1.148e-41, 0.000e+00],
       [6.390e-43, 0.000e+00],
       [0.000e+00, 0.000e+00]])

## I/O

### Saving and loading on disk

In [13]:
# Save one array
a = np.array([1, 2, 3])
npx.save('my_array', a)
npx.load('my_array')

array([1., 2., 3.])

In [14]:
# Save a list of arrays
b = np.array([4, 6, 8])
npx.savez('my_arrays', *[a, b])
npx.load('my_arrays')

{'arr_0': array([1., 2., 3.]), 'arr_1': array([4., 6., 8.])}

### Saving and loading text files

In [15]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

## Data types

In [16]:
# np.int64    # Signed 64-bit integer types
# np.float32  # Standard double-precision floating point
# np.complex  # Complex numbers represented by 128 floats
# np.bool     # Boolean type storing TRUE and FALSE values
# np.object   # Python object type
# np.string_  # Fixed-length string type
# np.unicode_ # Fixed-length unicode type

## Inspecting your array

In [17]:
a.shape # Array dimensions

(3,)

In [18]:
len(a) # Length of array

3

In [19]:
b.ndim # Number of array dimensions

1

In [20]:
b.size # Number of array elements

3

In [21]:
b.dtype # Data type of array elements

dtype('float32')

In [22]:
# b.dtype.name # Name of data type

In [23]:
b.astype('int') # Convert an array to a different type

array([4, 6, 8], dtype=int64)

## Asking For Help

In [24]:
# np.info(np.ndarray.dtype)

## Array mathematics

### Arithmetic operations

In [25]:
a - b # Subtraction

array([-3., -4., -5.])

In [26]:
np.subtract(a, b) # Subtraction

array([-3., -4., -5.])

In [27]:
b + a # Addition

array([ 5.,  8., 11.])

In [28]:
np.add(b, a) # Addition

array([ 5.,  8., 11.])

In [29]:
a / b # Division

array([0.25      , 0.33333334, 0.375     ])

In [30]:
np.divide(a,b) # Division

array([0.25      , 0.33333334, 0.375     ])

In [31]:
a * b # Multiplication

array([ 4., 12., 24.])

In [32]:
np.multiply(a, b) # Multiplication

array([ 4., 12., 24.])

In [33]:
np.exp(b) # Exponentiation

array([  54.59815,  403.4288 , 2980.958  ])

In [34]:
np.sqrt(b) # Square root

array([2.       , 2.4494898, 2.828427 ])

In [35]:
np.sin(a) # Sines of an array

array([0.84147096, 0.9092974 , 0.14112   ])

In [36]:
np.cos(b) # Element-wise cosine

array([-0.6536436 ,  0.96017027, -0.14550003])

In [37]:
np.log(a) # Element-wise natural logarithm

array([0.       , 0.6931472, 1.0986123])

In [38]:
a.dot(b) # Dot product

array(40.)

### Comparison

### Aggregate functions

In [39]:
a.sum() # Array-wise sum

array(6.)

In [40]:
# a.min() # Array-wise minimum value

In [41]:
c = np.array(([[1,2,3], [2,3,4]]))
# c.max(axis=0) # Maximum value of an array row

In [42]:
# c.cumsum(axis=1) # Cumulative sum of the elements

In [43]:
a.mean() # Mean

array(2.)

In [44]:
# b.median() # Median

In [45]:
# a.corrcoef() # Correlation coefficient

In [46]:
# np.std(b) # Standard deviation

## Copying arrays

In [47]:
# a.view() # Create a view of the array with the same data

In [48]:
np.copy(a) # Create a copy of the array

array([1., 2., 3.])

In [49]:
a.copy() # Create a deep copy of the array

array([1., 2., 3.])

## Sorting Arrays

In [50]:
# a.sort() # Sort an array

In [51]:
# c.sort(axis=0) # Sort the elements of an array's axis

## Subsetting, slicing, indexing

### Subsetting

In [52]:
a[2] # Select the element at the 2nd index 3

array(3.)

In [53]:
c[0,1] # Select the element at row 1 column 2

array(2.)

### Slicing

In [54]:
a[0:2] # Select items at index 0 and 1

array([1., 2.])

In [55]:
c[0:2,1] # Select items at rows 0 and 1 in column 1

array([2., 3.])

In [56]:
c[:1] # Select all items at row 0

array([[1., 2., 3.]])

In [57]:
# c[1,...] # Same as [1,:,:]

In [58]:
a[ : :-1] #Reversed array a array([3, 2, 1])

array([3., 2., 1.])

### Boolean Indexing

In [59]:
# a[a<2] # Select elements from a less than 2

### Fancy indexing

In [60]:
c[[1,0,1,0], [0,1,2,0]] # Select elements (1,0),(0,1),(1,2) and (0,0)

array([2., 2., 4., 1.])

In [61]:
c[[1,0,1,0]][:,[0,1,2,0]] # Select a subset of the matrix’s rows

array([[2., 3., 4., 2.],
       [1., 2., 3., 1.],
       [2., 3., 4., 2.],
       [1., 2., 3., 1.]])

## Array manipulation

### Transposing array

In [62]:
np.transpose(c) # Permute array dimensions

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

In [63]:
c.T # Permute array dimensions

array([[1., 2.],
       [2., 3.],
       [3., 4.]])

### Changing array shape

In [64]:
# b.ravel() # Flatten the array

In [65]:
# c.reshape(3,-2) # Reshape, but don’t change data

### Adding and removing elements

In [66]:
# c.resize((6,2)) # Return a new array with shape (6, 2)

In [67]:
# np.append(h,g) # Append items to an array

In [68]:
# np.insert(a, 1, 5) # Insert items in an array

In [69]:
# np.delete(a, [1]) # Delete items from an array

### Combining arrays

In [70]:
np.concatenate((a,b),axis=0) # Concatenate arrays

array([1., 2., 3., 4., 6., 8.])

In [71]:
# np.vstack((a,b)) # Stack arrays vertically (row-wise)

In [72]:
# np.r_[e,f] # Stack arrays vertically (row-wise)

In [73]:
# np.hstack((e,f)) # Stack arrays horizontally (column-wise)

In [74]:
# np.column_stack((a,d)) # Create stacked column-wise arrays

In [75]:
# np.c_[a,d] # Create stacked column-wise arrays

### Splitting arrays

In [76]:
# np.hsplit(a,3) # Split the array horizontally at the 3rd index

In [77]:
# np.vsplit(c,2) # Split the array vertically at the 2nd index

## Use GPUs

Prerequisites: A GPU exists and GPU-enabled MXNet is installed.

In [78]:
npx.num_gpus()  # Query number of GPUs

1

In [79]:
npx.gpu(0), npx.gpu(1)  # Context for the first and second GPUs

(gpu(0), gpu(1))

In [80]:
gpu_0 = npx.gpu(0) if npx.num_gpus() > 1 else npx.cpu()
g0 = np.zeros((2,3), device=gpu_0)  # Create array on GPU 0
g0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
gpu_1 = npx.gpu(1) if npx.num_gpus() > 2 else npx.cpu()
g1 = np.random.uniform(size=(2,3), device=gpu_1)  # Create array on GPU 1
g1

array([[0.5488135 , 0.5928446 , 0.71518934],
       [0.84426576, 0.60276335, 0.8579456 ]])

In [82]:
# Copy to another GPU
g1.copyto(gpu_0)

array([[0.5488135 , 0.5928446 , 0.71518934],
       [0.84426576, 0.60276335, 0.8579456 ]])

In [83]:
# Return itself if matching the device, otherwise copy
g1.copyto(gpu_0), g1.copyto(gpu_0)

(array([[0.5488135 , 0.5928446 , 0.71518934],
        [0.84426576, 0.60276335, 0.8579456 ]]),
 array([[0.5488135 , 0.5928446 , 0.71518934],
        [0.84426576, 0.60276335, 0.8579456 ]]))

In [84]:
g1.device  # Query the device an array is on

cpu(0)

In [85]:
## The computation is performed by the devices on which the input arrays are
g0 + g1.copyto(gpu_0)

array([[0.5488135 , 0.5928446 , 0.71518934],
       [0.84426576, 0.60276335, 0.8579456 ]])

## Auto differentiation

In [86]:
a.attach_grad() # Allocate gradient for a variable
a.grad # access the gradient

array([0., 0., 0.])

Compute the $\nabla_a b=\exp(2a)^T a$

In [87]:
from mxnet import autograd

with autograd.record():
    b = np.exp(2*a).dot(a)
b.backward()
a.grad

array([  22.167168,  272.99075 , 2824.0015  ])

**Acknowledgement**

Adapted from www.datacamp.com.